src/main.c

```console
$ ./lpac notification remove
Usage: ./lpac notification retrieve <seqNumber>
$ ./lpac notification retrieve
Unknown command: retrieve
```

fix: notification typo error

---

.github/workflows/build.yaml

- Download the prebuilt libcurl.dll and package it into the final release zip file
- Cross build for Windows onLlinux, drop msys2 to improve build speed

test Windows prebuilt curl build

---

euicc/es10x.c
euicc/es9p.c
euicc/euicc.h
euicc/interface.c
euicc/interface.h
interface/apdu/at.c
interface/apdu/pcsc.c
interface/apdu/stdio.c
interface/http/curl.c
interface/http/stdio.c

Needed for use with JNI, when mapping Java objects to these interface structs.

Pass euicc_ctx to all interface functions

---

euicc/es9p.c

This is required to compile with AOSP where `-Werror=return-type` is enforced.

Add return value to unimplemented es9p function

---

CMakeLists.txt
dlfcn-win32/dlfcn.c
interface/http/curl.c
src/CMakeLists.txt
src/dlsym_interface.c

- Use RPATH on Linux/macOS to ensure it will search directory that contains lpac executable file.
- Windows doesnn't has RPATH, but it will search executable file directory by default. And CMake will ignore BUILD_RPATH property on Windows safely.
- BUILD_RPATH doesn't affect files after `cmake --install`, but we doesn't declare install rule now (And we use RUNTIME_OUTPUT_DIRECTORY so we actually use non-install-style). If we need install-style in future, we can set INSTALL_RPATH_USE_LINK_PATH property so CMake will ensure it will work.

feat: $PWD independent executable file

---

README.md
euicc/es10cex.c
euicc/es10cex.h
src/applet/chip/info.c

> The "number of installed application" value field of extCardResource SHALL be set to '00'.
from [SGP.22 v2.5, 189p](https://www.gsma.com/esim/wp-content/uploads/2023/05/SGP.22-v2.5.pdf#page=189)
> The extCardResource field is defined in ETSI TS 102 226 [39]. This field includes the
current total available memory, expressed in bytes, for Profile download and installation.
> The "number of installed application" value field of extCardResource SHALL be set to '00'.
from [SGP.22 v3.0 (draft), 217p](https://www.gsma.com/esim/wp-content/uploads/2022/10/SGP.22-v3.0-1.pdf#page=217)

chore: remove installed app field

---

src/CMakeLists.txt

All UNIX like OS use $ORIGIN except f**king macOS, who use @loader_path.
Ref: https://lekensteyn.nl/rpath.html

fix: RPATH in macOS, who use @loader_path instead of $ORIGIN

---

CMakeLists.txt
README.md
interface/http/curl.c
src/dlsym_interface.c

Cygwin will not define `WIN32` and the binary built with `WIN32` defined will report an error `APDU library broken: missing libapduinterface_init`. Cygwin also does not define `_WIN32`, so check `__CYGWIN__` is defined.
For Mingw, `_WIN32` is suitable for more general situations, as `WIN32` will not be defined with some particular `-std` option

Fix Cygwin build

---

README.md
interface/apdu/CMakeLists.txt
interface/apdu/gbinder_hidl.c

This allows users of distributions like Droidian (which uses Android HALs to run GNU/Linux userspace) to manage eSIMs directly on device.
Currently only the HIDL version is implemented, which covers all SoCs released before Android 13. Newer device will require a different AIDL implementation.
As part of this change, the PCSC backend is now also made optional but enabled by default. PCSC can be disabled with `-DLPAC_APDU_INTERFACE_PCSC=OFF`, and GBinder can be enabled with `-DLPAC_APDU_INTERFACE_GBINDER=ON`.

Add GBinder backend for HIDL-based libhybris devices

---

.gitignore
cmake/git-version.cmake
src/CMakeLists.txt
src/applet/version.c
src/applet/version.h
src/main.c
src/version.h.in

```console
$ ./lpac version | jq
{
"type": "lpa",
"payload": {
"code": 0,
"message": "success",
"data": "v2.0.0-alpha.3-6-ge324419-dirty"
}
}
```

add version applet

---

cmake/git-version.cmake

if fetch depth is 1 and no tags, then
```console
$ ./lpac version | jq
{
"type": "lpa",
"payload": {
"code": 0,
"message": "success",
"data": "e090684"
}
}
```
see https://git-scm.com/docs/git-describe#Documentation/git-describe.txt---always

fix version applet

---

CMakeLists.txt
euicc/CMakeLists.txt
euicc/libeuicc.pc.in

...based on option LPAC_DYNAMIC_LIBEUICC, defaults to OFF.
This makes it possible to use libeuicc on Linux without submoduling.
Note that this would require any future breaking change to increment the MAJOR version of the project in the main CMakeLists.txt. This version number is now a public interface and must be maintained.
As part of this commit, I have modified the version code in CMakeLists to match the current release version.

feat: Allow libeuicc to be installed as a dynamic library

---

euicc/es10b.c
euicc/es10b.h
src/applet/chip/info.c

Related Procedures: Profile Download and Installation
Function Provider entity: ISD-R (LPA Services)
Description: This function retrieves the Rules Authorisation Table (RAT) from the eUICC. It can be called at any time. The RAT is used by the LPA to determine if a Profile containing PPRs can be installed, conditionally with End User Consent, on the eUICC as defined in section [2.9.2.4](https://www.gsma.com/esim/wp-content/uploads/2020/06/SGP.22-v2.2.2.pdf#page=46).
The command data SHALL be coded as follows:
```asn1
GetRatRequest ::= [67] SEQUENCE { -- Tag 'BF43'
-- No input data
}
```
```asn1
GetRatResponse ::= [67] SEQUENCE { -- Tag 'BF43'
rat RulesAuthorisationTable
}
RulesAuthorisationTable ::= SEQUENCE OF ProfilePolicyAuthorisationRule
ProfilePolicyAuthorisationRule ::= SEQUENCE { …
```

feat: add ES10b#GetRAT Support

---

README.md
src/applet/profile/download.c

usage example:
```console
$ lpac profile download -h
Usage: download [OPTIONS]
-s SM-DP+ Domain
-m Matching ID
-i IMEI
-c Confirmation Code (Password)
-a Activation Code (e.g: 'LPA:***')
-h This help info
$ lpac profile download -a "LPA:1$<smdp>$<ac_token>$<oid>$<cc>" -c "confirmation-code"
....
```

feat: add profile download activation code parsing

---

CMakeLists.txt

Otherwise, we will get the wrong RPATH `lib/lpac`.

fix: use CMAKE_INSTALL_FULL_* to get absolute path

---

src/applet/profile/delete.c

This was incorrectly identified as the disable function.

profile: fix error message for delete function

---

CMakeLists.txt

They use libc6 rather than libc.
resolve #105

chore(cpack): fix libc name on Debian

---

README.md

Written with GTK4 and Libadwaita it's targetting Linux Mobile distributions such as postmarketOS or Mobian.
See also: https://lucaweiss.eu/post/2024-06-24-esim-manager-for-mobile-linux/

docs: Add link to lpa-gtk UI for lpac

---

docs/USAGE.md

Make sure it's visible in the usage documentation that these parameters exist since they make life easier.
Fixes #127
---
I tried following the format for the other parameters in this document, let me know if I should change anything.

docs: Add parameters for 'notification process'

---

src/applet/notification/process.c
src/applet/notification/remove.c

Although POSIX said user should check errno instead of return value,
but errno may not be set when no conversion is performed according to C99.
Check nptr is same as str_end to ensure there is no conversion.
Signed-off-by: Celeste Liu <CoelacanthusHex@gmail.com>

fix: ensure "no conversion" result is checked correctly 

---

src/applet/notification/process.c
src/applet/notification/remove.c
src/applet/profile/discovery.c
src/applet/profile/download.c

* optind will be the index of the first mismatched argument, so use it directly.
* use while instead of for

refactor: optimize getopt() usage

---

euicc/euicc.c
euicc/euicc.h

This is useful on mobile devices where larger MTU + faster baud rate can result in 0x6601 checksum errors. This is going to be used in OpenEUICC (lpac-jni) to set the mss lower for removable eUICCs.

Expose es10x max segment size as an option in euicc_ctx

---

docs/ENVVARS.md
driver/CMakeLists.txt
driver/apdu/mbim.c
driver/apdu/mbim.h
driver/apdu/mbim_helpers.c
driver/apdu/mbim_helpers.h
driver/driver.c

Add an APDU backend for MBIM devices.
The MBIM device path can be passed via the MBIM_DEVICE environment variable. We'll default to /dev/cdc-wdm0.
By default we will not operate through the mbim-proxy. Set MBIM_USE_PROXY to 1 to enable this.
Like QMI devices, use UIM_PORT to select the active SIM slot.
Tested on Semtech EM9191 and EM7590.
resolve #94

driver: apdu: add MBIM backend

---

.github/workflows/build.yaml
CMakeLists.txt
scripts/build-ci.sh

* Better performance, small size, in theory.
* Cover more test points.

chore: enable LTO by default and add w/o LTO CI for debug

---

euicc/CMakeLists.txt

It's meaningless for other platforms. And ld.gold doesn't support so if
LTO was enabled we will get invalid arguments.
address #152
Signed-off-by: Coelacanthus <uwu@coelacanthus.name>

fix: only apply --export-all-symbol on Windows

---

docs/ENVVARS.md
src/main.c

euicc: added support for multiple AIDs
- Added env variable "LPAC_CUSTOM_ISD_R_AID" for user defined AIDs
- Added documentation for new env var
Closes #157
Closes #175
Not tested for #157, feedback appreciated.

euicc: added support for multiple AIDs

---

driver/apdu/pcsc.c

> For a human readable representation of an error the function pcsc_stringify_error() is declared in pcsclite.h.
>
> This function is not available on Microsoft(R) winscard API and is pcsc-lite specific.
from https://github.com/LudovicRousseau/PCSC/blob/f0f4fa1586f1cc695ad42c88d19dc4f15bfa3c71/src/winscard.c#L68-L70
```console
$ ./output/lpac chip
SCardConnect() failed: 80100009 (Unknown reader specified.)
{"type":"lpa","payload":{"code":-1,"message":"euicc_init","data":""}}
```

feat: human readable error code (pcsclite only)

---

src/main.c

> This class encapsulates the Application Identifier (AID) associated with an applet. An AID is defined in ISO 7816-5 to be a sequence of bytes between 5 and 16 bytes in length.
see https://docs.oracle.com/javacard/3.0.5/api/javacard/framework/AID.html
- https://cdn.standards.iteh.ai/samples/19980/8ff6c7ccc9254fe4b7a8a21c0bf59424/ISO-IEC-7816-5-1994.pdf

feat: improve isd-r aid handling

---

CMakeLists.txt

This creates a `compile_commands.json` file that can then be used by the `cland` tool.

CMakeLists.txt: enable CMAKE_EXPORT_COMPILE_COMMANDS by default

---

driver/apdu/qmi.c

`calloc()` also zeros all elements.

driver/apdu/qmi.c: use calloc instead of malloc

---

driver/apdu/qmi.c
driver/apdu/qmi_helpers.c
driver/apdu/qmi_helpers.h
driver/apdu/qmi_qrtr.c

While the QMI driver which goes to /dev/foobar wants to go through the qmi-proxy to not have to exclusively claim the device, the QMI-over-QRTR driver doesn't work with the PROXY flag and just leads to the error
error: open QMI device failed: endpoint hangup
Fix this by passing the correct flag to qmi_device_open from both APDU drivers.
Closes: #215
Fixes: 3bde4a1 (" driver(APDU): add QMI backend (#131)")

driver: apdu: qmi*: Pass correct open flag for QRTR driver

---

CMakeLists.txt

Due to the CMake minimum version bump, this policy is enabled by default.

CMakeLists.txt: remove CMP0069

---

.gitignore
CMakeLists.txt

This way, every out-of-source build folder will be ignored.

cmake: automatically create .gitignore in the build folder

---

driver/apdu/at.c

Some devices have a difference in format and do not add a space.
Simcom A7908E:
AT+CGLA=1,16,"81E2910003BF3C00"
+CGLA:4,"611A"
OK

driver: apdu: at: don't expect space after "+CGLA:"

---

driver/apdu/mbim.c

When waiting for the sim to become available after potentially switching, we don't actually do much waiting. We're basically only delayed by the speed of the communication here. If the switch doesn't happen quickly enough, this may result in us deciding a sim didn't become available, but subsequent calls will produce usable results.
So introduce a small 50 ms wait time, so we limit the total waiting time to about 1 second. This I think should be enough for the sim to actually become available.
resolve #241

driver: apdu: mbim: sleep while waiting for sim

---

driver/apdu/mbim.c

When we do not need to switch sims, the output of the program says
error: no channel response received: Failure
but when we do switch, we say
sim did not become available
To make this behavior more consistent, don't say anything about the sim status and continue as if we didn't have to switch.

driver: apdu: mbim: make sim behavior more consistent

---

src/main.c

if driver name is NULL then select first available driver
https://github.com/estkme-group/lpac/blob/0fd05d039eaab1b4ab8ecd7c38c439aef9f18da4/driver/driver.c#L76-L95

refactor: move fallback logic to _find_driver()

---

driver/apdu/pcsc.c

It may be this reader is used by another process (e.g. OpenPGP Card), shouldn't abort iteration.

fix(pcsc): skip reader if meet sharing violation

---

src/applet/profile/download.c
src/main.c

```console
$ ./lpac profile download -a $'LPA:1\$example.com\$test\ntest'
{"type":"progress","payload":{"code":0,"message":"es10b_cancel_session","data":"example.com"}}
{"type":"progress","payload":{"code":0,"message":"es9p_cancel_session","data":"example.com"}}
{"type":"lpa","payload":{"code":-1,"message":"matching_id","data":"invalid format, contains character not alphanumeric or dash"}}
```

feat: strict matching id checking in activation code

---

docs/LINUX-DIST.md

proof: https://downloads.openwrt.org/releases/24.10.2/packages/x86_64/packages/lpac_2.1.0-r1_x86_64.ipk

docs: update openwrt minimum available release

---

cmake/git-version.cmake
src/CMakeLists.txt
src/applet/version.h
src/version.h.in

* When git and .git directory is available, it append revision and commit id of HEAD to version string.
* Otherwise, it use version string defined in project() command.
* Use target_compile_definitions() instead of configure header file, avoid common header name conflict.

refactor: new LPAC_VERSION handling

---

driver/http/curl.c

```console
$ ./lpac driver http info | jq
{
"type": "driver",
"payload": {
"curl_version": "libcurl/8.7.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.64.0"
}
}
```

feat(driver): read curl version

---

src/applet/profile/download.c

```
./lpac profile download -a 'lpa:1$...$...'
```

fix(src): case-insensitive activation code scheme

---

CMakeLists.txt
src/applet/notification/dump.c
src/jprint.c
utils/lpac/utils.c
utils/lpac/utils.h

F**king cJSON library has almost no documentation. There is no one who will tell you the internal allocator will be used to allocate the string returned by cJSON_Print* series functions, and it SHALL be released using cJSON_free() to pair with the allocator!
And Windows has a different behavior from *nix. On *nix, although the library is built as a static library, the libc is still dynamically linked. But on Windows, it will statically link the CRT by default. It will lead there are two different instances of CRT, and then the malloc()/free() seen by cjson and other parts of lpac
are different.
supersedes and close #328

fix(cJSON): invoke wrong memory release function

---

CMakeLists.txt
driver/CMakeLists.txt
euicc/CMakeLists.txt

So it can be used by lpac-utils.

refactor(cmake): move some options to global
